
import { Question } from './types';

export const QUIZ_QUESTIONS: Question[] = [
  // Capítulo 1 – História das Embalagens
  {
    id: 1,
    chapter: 1,
    question: "Qual das seguintes inovações da Revolução Industrial revolucionou a conservação de alimentos por longos períodos?",
    options: ["Vidro prensado", "Papelão ondulado", "Lata de estanho", "Impressão de rótulos"],
    correctAnswerIndex: 2,
  },
  {
    id: 2,
    chapter: 1,
    question: "Na década de 1970, qual fator impulsionou a embalagem a ganhar uma função de comunicação e marketing mais forte?",
    options: ["A invenção do plástico", "O surgimento dos supermercados e do autoatendimento", "A preocupação com a sustentabilidade", "A criação do código de barras"],
    correctAnswerIndex: 1,
  },
  {
    id: 3,
    chapter: 1,
    question: "Antes da Revolução Industrial, quais materiais eram comumente usados para criar as primeiras formas de embalagem?",
    options: ["Plásticos e metais leves", "Folhas, peles de animais e argila", "Vidro soprado e papel cartão", "Alumínio e polímeros"],
    correctAnswerIndex: 1,
  },
  {
    id: 4,
    chapter: 1,
    question: "O que são 'Filigranas' no contexto de elementos visuais de uma embalagem?",
    options: ["Textos circulares que simulam selos de certificação", "Elementos gráficos explosivos para promoções", "Faixas que destacam slogans", "Detalhes ornamentais que conferem sofisticação"],
    correctAnswerIndex: 3,
  },
  {
    id: 5,
    chapter: 1,
    question: "A invenção do papelão ondulado foi crucial para substituir qual material no transporte de produtos?",
    options: ["Barris de metal", "Caixas de madeira", "Sacos de tecido", "Potes de cerâmica"],
    correctAnswerIndex: 1,
  },
  {
    id: 6,
    chapter: 1,
    question: "A partir dos anos 2000, qual tendência principal influenciou a criação de embalagens, incorporando tecnologias como QR codes?",
    options: ["A busca por custos mais baixos", "O aumento da produção em massa", "O avanço da sustentabilidade e interatividade", "A padronização de formatos"],
    correctAnswerIndex: 2,
  },
  {
    id: 7,
    chapter: 1,
    question: "Qual civilização antiga foi pioneira no uso de ânforas de cerâmica para padronizar o transporte de líquidos?",
    options: ["Egípcios", "Gregos", "Romanos", "Chineses"],
    correctAnswerIndex: 2,
  },
  // Capítulo 2 – Metodologia das Embalagens
  {
    id: 8,
    chapter: 2,
    question: "Qual das 5 funções principais da embalagem está relacionada à sua capacidade de atrair o cliente no ponto de venda e ser um 'vendedor silencioso'?",
    options: ["Conter", "Proteger", "Transportar", "Vender"],
    correctAnswerIndex: 3,
  },
  {
    id: 9,
    chapter: 2,
    question: "Garrafas de vidro de refrigerante que são devolvidas à indústria para higienização e reuso são classificadas como:",
    options: ["Embalagens descartáveis", "Embalagens reutilizáveis", "Embalagens retornáveis", "Embalagens primárias"],
    correctAnswerIndex: 2,
  },
  {
    id: 10,
    chapter: 2,
    question: "Um pote de geleia que, após o consumo do produto, é usado pelo consumidor para guardar temperos é um exemplo de embalagem:",
    options: ["Descartável", "Retornável", "Reutilizável", "Secundária"],
    correctAnswerIndex: 2,
  },
  {
    id: 11,
    chapter: 2,
    question: "Qual aspecto de design da embalagem se refere à facilidade de abrir, fechar e manusear o produto?",
    options: ["Apelo visual", "Funcionalidade e usabilidade", "Logística", "Proteção"],
    correctAnswerIndex: 1,
  },
  {
    id: 12,
    chapter: 2,
    question: "A função 'unitização' da embalagem permite:",
    options: ["Proteger o produto contra impactos mecânicos", "Agrupar produtos em unidades menores ou porções individuais", "Comunicar a data de validade e os ingredientes", "Facilitar o empilhamento durante o transporte"],
    correctAnswerIndex: 1,
  },
  {
    id: 13,
    chapter: 2,
    question: "Qual é a principal desvantagem ambiental das embalagens descartáveis?",
    options: ["Alto custo de produção", "Geração de resíduos sólidos", "Dificuldade de transporte", "Baixa resistência"],
    correctAnswerIndex: 1,
  },
  {
    id: 14,
    chapter: 2,
    question: "A função de 'proteger' a embalagem inclui a proteção contra qual dos seguintes fatores?",
    options: ["Concorrência de mercado", "Variações de preço", "Microrganismos, umidade e impactos mecânicos", "Decisão de compra do consumidor"],
    correctAnswerIndex: 2,
  },
  // Capítulo 3 – Linguagem Visual para PDV
  {
    id: 15,
    chapter: 3,
    question: "Na psicologia das cores, qual cor é frequentemente usada em embalagens de alimentos para estimular o apetite e criar um senso de urgência?",
    options: ["Azul", "Verde", "Vermelho", "Preto"],
    correctAnswerIndex: 2,
  },
  {
    id: 16,
    chapter: 3,
    question: "Qual cor é amplamente associada à confiança, tranquilidade e segurança, sendo comum em produtos de higiene e tecnologia?",
    options: ["Amarelo", "Azul", "Laranja", "Vermelho"],
    correctAnswerIndex: 1,
  },
  {
    id: 17,
    chapter: 3,
    question: "Qual é o primeiro passo na metodologia de projeto de uma embalagem, que reúne informações sobre o produto, público e objetivos?",
    options: ["Desenvolvimento do desenho", "Pesquisa de campo", "Produção e testes", "Briefing"],
    correctAnswerIndex: 3,
  },
  {
    id: 18,
    chapter: 3,
    question: "O elemento visual conhecido como 'Splash' é usado em embalagens para:",
    options: ["Conferir um toque artesanal com fontes manuscritas", "Transmitir sofisticação com detalhes ornamentais", "Chamar a atenção para promoções ou informações importantes", "Destacar o logotipo da marca em uma faixa"],
    correctAnswerIndex: 2,
  },
  {
    id: 19,
    chapter: 3,
    question: "A cor verde em uma embalagem geralmente comunica valores relacionados a:",
    options: ["Luxo e poder", "Alegria e otimismo", "Natureza, sustentabilidade e saúde", "Paixão e energia"],
    correctAnswerIndex: 2,
  },
  {
    id: 20,
    chapter: 3,
    question: "A escolha da tipografia em uma embalagem influencia diretamente:",
    options: ["A resistência do material", "A validade do produto", "A leitura e a percepção do consumidor sobre a marca", "O custo de transporte"],
    correctAnswerIndex: 2,
  },
  {
    id: 21,
    chapter: 3,
    question: "O que o impacto cultural das cores significa para o design de embalagens globais?",
    options: ["Que todas as cores têm o mesmo significado em todo o mundo", "Que o significado das cores pode variar entre culturas e deve ser considerado", "Que apenas as cores primárias devem ser usadas", "Que a cultura não influencia a percepção das cores"],
    correctAnswerIndex: 1,
  },
  // Capítulo 4 – Embalagens Semirrígidas
  {
    id: 22,
    chapter: 4,
    question: "Qual é o principal processo de acabamento utilizado para criar dobras e formatos em embalagens semirrígidas?",
    options: ["Laminação", "Impressão offset", "Corte e vinco", "Termoformagem"],
    correctAnswerIndex: 2,
  },
  {
    id: 23,
    chapter: 4,
    question: "O papel cartão 'Triplex' se diferencia do 'Duplex' por ter:",
    options: ["Maior resistência à água", "Uma terceira camada branca no verso, permitindo impressão em ambas as faces", "Ser feito exclusivamente de material reciclado", "Coloração amarronzada (kraft)"],
    correctAnswerIndex: 1,
  },
  {
    id: 24,
    chapter: 4,
    question: "No papelão ondulado, qual tipo de onda oferece o melhor amortecimento contra impactos, sendo ideal para produtos frágeis?",
    options: ["Onda E (microondulado)", "Onda B", "Onda A", "Onda C"],
    correctAnswerIndex: 2,
  },
  {
    id: 25,
    chapter: 4,
    question: "Embalagens longa vida (cartonadas) utilizam uma camada de qual material para criar uma barreira eficiente contra oxigênio e luz?",
    options: ["Papel cartão SBS", "Filme de polietileno (PE)", "Alumínio", "Tecido"],
    correctAnswerIndex: 2,
  },
  {
    id: 26,
    chapter: 4,
    question: "A fôrma de corte e vinco é utilizada em qual tipo de máquina?",
    options: ["Impressora digital", "Máquina de laminação", "Máquinas planas ou rotativas de corte", "Extrusora de plástico"],
    correctAnswerIndex: 2,
  },
  {
    id: 27,
    chapter: 4,
    question: "Qual tipo de fundo de caixa semirrígida possui travas que facilitam a montagem manual, sem necessidade de cola?",
    options: ["Fundo simples", "Fundo automático", "Fundo semiautomático", "Fundo colado"],
    correctAnswerIndex: 2,
  },
  {
    id: 28,
    chapter: 4,
    question: "O papel cartão SBS (Solid Bleached Sulfate) é tipicamente utilizado para:",
    options: ["Embalagens ecológicas com apelo rústico", "Caixas de transporte que exigem alta resistência", "Embalagens de luxo e produtos sofisticados", "Produtos que precisam de barreira contra umidade"],
    correctAnswerIndex: 2,
  },
  // Capítulo 5 – Embalagens Flexíveis
  {
    id: 29,
    chapter: 5,
    question: "O que é um 'stand-up pouch'?",
    options: ["Uma embalagem flexível que fica em pé na prateleira", "Um tipo de rótulo termoencolhível", "Uma sacola de papel para delivery", "Uma embalagem a vácuo para carnes"],
    correctAnswerIndex: 0,
  },
  {
    id: 30,
    chapter: 5,
    question: "Qual substrato é considerado uma barreira absoluta contra luz, umidade e oxigênio em embalagens flexíveis?",
    options: ["Papel Kraft", "Filme PET", "Filme de Polietileno (PE)", "Folha de Alumínio"],
    correctAnswerIndex: 3,
  },
  {
    id: 31,
    chapter: 5,
    question: "O processo de 'laminação' em embalagens flexíveis consiste em:",
    options: ["Imprimir a arte gráfica diretamente no material", "Unir permanentemente dois ou mais substratos diferentes", "Cortar a embalagem no formato final", "Aplicar um verniz para dar brilho"],
    correctAnswerIndex: 1,
  },
  {
    id: 32,
    chapter: 5,
    question: "Qual filme plástico é conhecido pela sua ótima resistência térmica e mecânica, sendo muito utilizado na camada externa de laminados?",
    options: ["Polietileno (PE)", "Polipropileno (PP)", "Poliéster (PET)", "Poliamida (PA)"],
    correctAnswerIndex: 2,
  },
  {
    id: 33,
    chapter: 5,
    question: "Na laminação, a camada que entra em contato direto com o produto e precisa ter propriedades de selagem é a:",
    options: ["Camada externa", "Camada intermediária", "Camada interna", "Camada de impressão"],
    correctAnswerIndex: 2,
  },
  {
    id: 34,
    chapter: 5,
    question: "Qual é o principal desafio ambiental das embalagens flexíveis multicamadas?",
    options: ["Seu alto peso, que aumenta o custo de transporte", "Sua complexidade, que dificulta a reciclagem", "O uso de materiais tóxicos em sua composição", "A baixa resistência a rasgos"],
    correctAnswerIndex: 1,
  },
  {
    id: 35,
    chapter: 5,
    question: "Embalagens do tipo 'flowpack' são tipicamente seladas por qual método?",
    options: ["Cola fria", "Costura", "Calor", "Grampos"],
    correctAnswerIndex: 2,
  },
  // Capítulo 6 – Embalagens Rígidas
  {
    id: 36,
    chapter: 6,
    question: "Qual processo de produção de plásticos é usado para criar peças com formas complexas, como tampas com rosca?",
    options: ["Sopro", "Termoformagem", "Injeção (moldagem por injeção)", "Extrusão"],
    correctAnswerIndex: 2,
  },
  {
    id: 37,
    chapter: 6,
    question: "Garrafas de refrigerante são majoritariamente produzidas com qual tipo de plástico e por qual processo?",
    options: ["PEAD por extrusão-sopro", "PP por injeção", "PET por injeção-sopro", "PS por termoformagem"],
    correctAnswerIndex: 2,
  },
  {
    id: 38,
    chapter: 6,
    question: "O processo de 'prensagem-sopro' (press-blow) é preferível ao 'sopro-sopro' para embalagens de vidro que exigem:",
    options: ["Formatos mais complexos e artísticos", "Espessura de parede mais uniforme, como em potes largos", "Cores mais escuras para proteção UV", "Maior leveza e menor custo"],
    correctAnswerIndex: 1,
  },
  {
    id: 39,
    chapter: 6,
    question: "Latas de alumínio para bebidas são fabricadas principalmente pelo processo de:",
    options: ["Soldagem e fechamento", "Estampagem profunda", "Injeção de metal", "Termoformagem de alumínio"],
    correctAnswerIndex: 1,
  },
  {
    id: 40,
    chapter: 6,
    question: "Qual é a principal vantagem do vidro como material para embalagem?",
    options: ["Leveza e baixo custo", "Flexibilidade e maleabilidade", "Inércia química, impermeabilidade e percepção de qualidade", "Resistência a quedas e impactos"],
    correctAnswerIndex: 2,
  },
  {
    id: 41,
    chapter: 6,
    question: "Bioplásticos são materiais produzidos a partir de:",
    options: ["Petróleo com aditivos especiais", "Metais reciclados", "Matérias-primas renováveis como milho ou cana-de-açúcar", "Vidro moído e areia"],
    correctAnswerIndex: 2,
  },
  {
    id: 42,
    chapter: 6,
    question: "Bandejas de alimentos prontos e potes descartáveis são comumente fabricados pelo processo de:",
    options: ["Injeção-sopro", "Extrusão", "Termoformagem", "Rotomoldagem"],
    correctAnswerIndex: 2,
  },
  // Capítulo 7 – Pré-impressão
  {
    id: 43,
    chapter: 7,
    question: "Qual é a resolução mínima recomendada para imagens em impressão de alta qualidade?",
    options: ["72 dpi", "150 dpi", "300 dpi", "600 dpi"],
    correctAnswerIndex: 2,
  },
  {
    id: 44,
    chapter: 7,
    question: "O que é 'imposição' no processo de pré-impressão?",
    options: ["Corrigir as cores da imagem", "Aplicar um filtro para melhorar a nitidez", "Organizar as embalagens em uma folha para otimizar o uso do material", "Converter a fonte do texto em curvas"],
    correctAnswerIndex: 2,
  },
  {
    id: 45,
    chapter: 7,
    question: "A 'sangria' (bleed) em um arquivo para impressão serve para:",
    options: ["Adicionar um espaço em branco ao redor da arte", "Garantir que não haja bordas brancas após o corte", "Reduzir o tamanho do arquivo final", "Indicar as áreas de dobra da embalagem"],
    correctAnswerIndex: 1,
  },
  {
    id: 46,
    chapter: 7,
    question: "Para garantir a fidelidade da impressão, as imagens devem estar no modo de cor:",
    options: ["RGB", "LAB", "CMYK", "Grayscale"],
    correctAnswerIndex: 2,
  },
  {
    id: 47,
    chapter: 7,
    question: "Qual formato de arquivo é o mais seguro e padronizado para enviar à gráfica?",
    options: ["JPEG", "PNG", "PSD", "PDF/X"],
    correctAnswerIndex: 3,
  },
  {
    id: 48,
    chapter: 7,
    question: "O que é 'máscara de camada' e por que é útil no tratamento de imagens?",
    options: ["Uma técnica para aumentar a resolução da imagem", "Um filtro que adiciona cor à imagem", "Uma forma de apagar pixels permanentemente", "Uma técnica não destrutiva para ocultar partes da imagem"],
    correctAnswerIndex: 3,
  },
  {
    id: 49,
    chapter: 7,
    question: "Por que é importante manter uma 'margem de segurança' no design de embalagens?",
    options: ["Para a arte parecer maior", "Para evitar que elementos importantes como textos sejam cortados", "Para facilitar a aplicação de verniz", "Para aumentar a sangria"],
    correctAnswerIndex: 1,
  },
  // Capítulo 8 – Impressão
  {
    id: 50,
    chapter: 8,
    question: "Qual sistema de impressão é indireto e ideal para papel/cartão, oferecendo altíssima definição e a possibilidade de usar cores especiais como Pantone?",
    options: ["Serigrafia", "Flexografia", "Rotogravura", "Offset"],
    correctAnswerIndex: 3,
  },
  {
    id: 51,
    chapter: 8,
    question: "A serigrafia é conhecida por sua versatilidade e pela capacidade de:",
    options: ["Imprimir milhões de cópias por hora", "Ser o processo mais barato para qualquer tiragem", "Aplicar camadas espessas de tintas especiais (metálicas, fluorescentes)", "Imprimir apenas em papel"],
    correctAnswerIndex: 2,
  },
  {
    id: 52,
    chapter: 8,
    question: "Qual sistema de impressão utiliza uma fôrma flexível em relevo (clichê) e é dominante no mercado de embalagens flexíveis de alta tiragem?",
    options: ["Offset", "Flexografia", "Rotogravura", "Impressão digital"],
    correctAnswerIndex: 1,
  },
  {
    id: 53,
    chapter: 8,
    question: "A rotogravura utiliza cilindros metálicos gravados em baixo-relevo (encavográfico) e é caracterizada por:",
    options: ["Baixo custo inicial para os cilindros", "Qualidade superior e estabilidade em tiragens extremamente altas", "Ser ideal para pequenas tiragens e personalização", "Utilizar tintas à base de água exclusivamente"],
    correctAnswerIndex: 1,
  },
  {
    id: 54,
    chapter: 8,
    question: "A impressão de dados variáveis, como nomes diferentes em cada embalagem ou QR codes únicos, é uma capacidade da:",
    options: ["Impressão Offset tradicional", "Serigrafia manual", "Impressão Digital", "Rotogravura"],
    correctAnswerIndex: 2,
  },
  {
    id: 55,
    chapter: 8,
    question: "O cilindro 'anilox', essencial na flexografia, tem a função de:",
    options: ["Pressionar o substrato contra o clichê", "Transferir uma quantidade controlada de tinta para o clichê", "Secar a tinta após a impressão", "Gravar a imagem no clichê"],
    correctAnswerIndex: 1,
  },
  {
    id: 56,
    chapter: 8,
    question: "Qual processo de impressão é mais adequado para decorar frascos de vidro ou plástico com formatos irregulares?",
    options: ["Offset", "Rotogravura", "Flexografia", "Serigrafia"],
    correctAnswerIndex: 3,
  },
  {
    id: 57,
    chapter: 8,
    question: "A 'blanqueta' é um componente essencial em qual processo de impressão?",
    options: ["Serigrafia", "Offset", "Flexografia", "Digital"],
    correctAnswerIndex: 1,
  },
  {
    id: 58,
    chapter: 8,
    question: "A principal vantagem da flexografia e rotogravura sobre o offset em embalagens é a:",
    options: ["Maior qualidade de impressão em todos os casos", "Capacidade de imprimir em uma variedade maior de substratos, incluindo filmes plásticos", "Menor custo para pequenas tiragens", "Facilidade de setup e troca de trabalhos"],
    correctAnswerIndex: 1,
  },
  {
    id: 59,
    chapter: 8,
    question: "O efeito de 'squash' (um leve espalhamento da tinta nas bordas) é uma característica visual de qual sistema de impressão?",
    options: ["Rotogravura", "Offset", "Flexografia", "Serigrafia"],
    correctAnswerIndex: 2,
  },
  {
    id: 60,
    chapter: 8,
    question: "Qual sistema de impressão é mais competitivo para tiragens na casa das centenas de milhares ou milhões, como embalagens de salgadinhos?",
    options: ["Offset", "Serigrafia", "Impressão Digital", "Rotogravura"],
    correctAnswerIndex: 3,
  },
];
